# This configuration requires the custom golangci-lint binary built by
version: "2"

linters:
  default: none
  enable:
    # - diinterfacecheck
    - newinterfacecheck
  settings:
    custom:
      # diinterfacecheck:
      #   type: module
      #   description: detect concrete DI types
      newinterfacecheck:
        type: module
        description: detect concrete parameters in NewXxx functions
