# This configuration requires the custom golangci-lint binary built by
version: "2"

linters:
  default: none
  enable:
    - diinterfacecheck
  settings:
    custom:
      diinterfacecheck:
        type: module
        description: detect concrete DI types
